# Generated by Django 4.2.14 on 2024-08-08 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []  # noqa: RUF012

    operations = [  # noqa: RUF012
        migrations.CreateModel(
            name="BaseEvent",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "base_event",
            },
        ),
        migrations.CreateModel(
            name="Tournament",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "tournament",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("is_superuser", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("rating", models.IntegerField(default=0)),
                ("description", models.TextField(null=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[("PRIVATE", "PRIVATE"), ("PUBLIC", "PUBLIC")], default="PUBLIC", max_length=255
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("start_time", models.TimeField(null=True)),
                ("date", models.DateField(null=True)),
                ("latitude", models.FloatField(null=True)),
                ("longitude", models.FloatField(null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ("json", models.JSONField(null=True)),
                (
                    "base",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="event",
                        to="orm.baseevent",
                    ),
                ),
                ("participants", models.ManyToManyField(related_name="events", to="orm.user")),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="events", to="orm.tournament"
                    ),
                ),
            ],
            options={
                "db_table": "event",
            },
        ),
    ]
